version: '3.8'

services:
  pimeManagementdb:
    image: postgres:latest
    container_name: PimeManagement_db
    restart: always
    environment:
      POSTGRES_USER: alarcona
      POSTGRES_PASSWORD: password
      POSTGRES_DB: PimeManagementdb
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:

